
echo '/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\' >> /home/simon/Git/metadata_scraper/log_file.txt;
date >>/home/simon/Git/metadata_scraper/log_file.txt;
echo '\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/' >> /home/simon/Git/metadata_scraper/log_file.txt;
cd /home/simon/Git/metadata_scraper/;
git pull >> /home/simon/Git/metadata_scraper/log_file.txt;
sleep 1;
echo "running scraper...";
python3 /home/simon/Git/metadata_scraper/raw_code.py;
sleep 1;
cd /home/simon/Git/metadata_scraper/graphs;
python3 /home/simon/Git/metadata_scraper/graphs/graphs.py;
sleep 1;
cd /home/simon/Git/metadata_scraper/;
echo "Python programs completed -- writing .csv, .html and .json" >> /home/simon/Git/metadata_scraper/log_file.txt;
echo "commiting to GitHub and writing to log file";
echo "_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ " >> /home/simon/Git/metadata_scraper/log_file.txt;
git status >> /home/simon/Git/metadata_scraper/log_file.txt;
sleep 1;
git add * >> /home/simon/Git/metadata_scraper/log_file.txt;
sleep 1;
git commit -m "automatic shell commit" >> /home/simon/Git/metadata_scraper/log_file.txt;
sleep 1;
git push origin master >> /home/simon/Git/metadata_scraper/log_file.txt;
echo "script finished" >> /home/simon/Git/metadata_scraper/log_file.txt;
