cd /home/simon/Git/metadata_scraper/;
echo "running scraper...";
python3 /home/simon/Git/metadata_scraper/raw_code.py;
sleep 5;
echo "scraping and writing to csv complete" >> /home/simon/Git/metadata_scraper/log_file.txt;
echo "commiting to GitHub and writing to log file";
date >>/home/simon/Git/metadata_scraper/log_file.txt;
echo "_______________________________" >> /home/simon/Git/metadata_scraper/log_file.txt;
sleep 5;
git status;
sleep 2;
git add *;
sleep 2;
git commit -m "automatic shell commit" >> /home/simon/Git/metadata_scraper/log_file.txt;
sleep 2;
git push origin master;
sleep 2;
echo "Run finished and pushed to Repo";
