
echo '/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\' >> /home/admineo4geo/metadata_scraper/log_file.txt;
date >>/home/admineo4geo/metadata_scraper/log_file.txt;
echo '\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/' >> /home/admineo4geo/metadata_scraper/log_file.txt;
cd /home/admineo4geo/metadata_scraper/;
sleep 2;
git pull >> /home/admineo4geo/metadata_scraper/log_file.txt;
sleep 2;
echo "running scraper...";
python3 /home/admineo4geo/metadata_scraper/raw_code.py;
sleep 2;
cd /home/admineo4geo/metadata_scraper/graphs;
sleep 2;
python3 /home/admineo4geo/metadata_scraper/graphs/graphs.py;
sleep 2;
cd /home/admineo4geo/metadata_scraper/;
sleep 2;
echo "Python programs completed -- writing .csv, .html and .json" >> /home/admineo4geo/metadata_scraper/log_file.txt;
echo "commiting to GitHub and writing to log file";
echo "_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ " >> /home/admineo4geo/metadata_scraper/log_file.txt;
git status >> /home/admineo4geo/metadata_scraper/log_file.txt;
echo "script finished" >> /home/admineo4geo/metadata_scraper/log_file.txt;
sleep 2;
git add *;
sleep 2;
git commit -m "automatic shell commit";
sleep 2;
git push origin master;
sleep 2;
